<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>def</string>
        <string>mod</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~M</string>
    <key>name</key>
    <string>Modula 2</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\b(ABSOLUTE|ABSTRACT|ALL|AND|AND_THEN|ARRAY|AS|ASM|ATTRIBUTE|BEGIN|BINDABLE|BY|CASE|CLASS|CONST|CONSTRUCTOR|DEFINITION|DESTRUCTOR|DIV|DO|ELSE|ELSIF|END|EXCEPT|EXIT|EXPORT|EXPORTS|EXTERNAL|FAR|FILE|FINALIZATION|FINALLY|FOR|FORWARD|FROM|GOTO|IF|IMPLEMENTATION|IMPORT|IN|INHERITED|INITIALIZATION|INTERFACE|INTERRUPT|IS|LABEL|LIBRARY|LOOP|MOD|MODULE|NAME|NEAR|NIL|NOT|OBJECT|OF|ONLY|OPERATOR|OR|OR_ELSE|OTHERWISE|PACKED|PACKEDSET|POINTER|POW|PRIVATE|PROGRAM|PROPERTY|PROTECTED|PUBLIC|PUBLISHED|QUALIFIED|RECORD|REM|REPEAT|RESIDENT|RESTRICTED|RETRY|RETURN|SEGMENT|SET|SHL|SHR|THEN|TO|TRY|TYPE|UNIT|UNTIL|USES|VALUE|VAR|VIEW|VIRTUAL|WHILE|WITH|XOR)\b</string>
            <key>name</key>
            <string>keyword.control.modula2</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.prototype.modula2</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.prototype.modula2</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(PROCEDURE)\b\s+(\w+(\.\w+)?)(\(.*?\))?;\s*(?=ATTRIBUTE|FORWARD|EXTERNAL)</string>
            <key>name</key>
            <string>meta.function.prototype.modula2</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.modula2</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.modula2</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(PROCEDURE)\b\s+(\w+(\.\w+)?)</string>
            <key>name</key>
            <string>meta.function.modula2</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
            <key>name</key>
            <string>constant.numeric.modula2</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=--)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.whitespace.comment.leading.modula2</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>--</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.modula2</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>comment.line.double-dash.modula2.one</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.whitespace.comment.leading.modula2</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>//</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.modula2</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>comment.line.double-slash.modula2.two</string>
                </dict>
            </array>
        </dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.modula2</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>Double quoted strings are an extension and (generally) support C-style escape sequences.</string>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.modula2</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.modula2</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.modula2</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.modula2</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.modula2</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.modula2</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>''</string>
                    <key>name</key>
                    <string>constant.character.escape.apostrophe.modula2</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>block_comment</key>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\(\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.modula2</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#block_comment</string>
                </dict>
            </array>
            <key>end</key>
            <string>\*\)</string>
            <key>name</key>
            <string>comment.block.modula2.one</string>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.modula2</string>
    <key>uuid</key>
    <string>1d162476-0af3-43a0-8848-b713076b36c8</string>
</dict>
</plist>
